Work around PyD "reference not found" issue
Sometimes, when accessing string struct members in the array, that
action fails with:
> pyd/references.d(329): Error extracting D object: reference not found!

The object itself is present, so some odd memory management seems to be
going on here. Duplicating the appender output array seems to work
around this issue, so we'll do that for now.